apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: voting-app

commonLabels:
  app.kubernetes.io/part-of: voting-app

resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - migrations/job.yaml
  - vote-api/serviceaccount.yaml
  - vote-api/deployment.yaml
  - vote-api/service.yaml
  - vote-api/backendconfig.yaml
  - results-api/serviceaccount.yaml
  - results-api/deployment.yaml
  - results-api/service.yaml
  - results-api/backendconfig.yaml
  - tally-worker/serviceaccount.yaml
  - tally-worker/deployment.yaml

configMapGenerator:
  - name: app-config
    envs:
      - config/app-config.env
  - name: migrations-sql
    files:
      - ../../../migrations/0001_create_votes.up.sql
      - ../../../migrations/0001_create_votes.down.sql
      - ../../../migrations/0002_create_vote_results.up.sql
      - ../../../migrations/0002_create_vote_results.down.sql

generatorOptions:
  disableNameSuffixHash: false
