apiVersion: v1
kind: Service
metadata:
  name: results-api
  labels:
    app.kubernetes.io/name: results-api
  annotations:
    cloud.google.com/backend-config: '{"default":"results-api"}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: results-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
